routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'change-password'], function () {
        Route::get('', 'Auth\ChangePasswordController@showChangePasswordForm')->name('password.change');
        Route::post('', 'Auth\ChangePasswordController@changePassword');
    });

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('providers', 'ProviderController', ['except' => 'show']);
        Route::resource('categories', 'CategoryController', ['except' => 'show']);
    });
});

Route::get('/', 'FeedController@index')->name('feeds.index');

app/Models/Provider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $url
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 *
 * @property Category $category
 * @property Feed[]|\Illuminate\Support\Collection $feeds
 */
class Provider extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'url', 'category_id',
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function feeds(): HasMany
    {
        return $this->hasMany(Feed::class);
    }
}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProviderRequest;
use App\Models\Provider;
use App\Repositories\Contracts\CategoryRepository;
use App\Repositories\Contracts\ProviderRepository;
use Illuminate\Contracts\Translation\Translator;
use Illuminate\Contracts\View\Factory as ViewFactory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\Session\Store;
use Illuminate\View\View;

class ProviderController extends Controller
{
    /**
     * @var ProviderRepository
     */
    private $providers;

    /**
     * @var CategoryRepository
     */
    private $categories;

    public function __construct(
        ViewFactory $views,
        Store $session,
        Redirector $redirector,
        Translator $translator,
        ProviderRepository $providers,
        CategoryRepository $categories
    ) {
        parent::__construct($views, $session, $redirector, $translator);
        $this->providers = $providers;
        $this->categories = $categories;
    }

    public function index(): View
    {
        return $this->views->make('provider.index', [
            'groupedProviders' => $this->providers->findGroupedByCategory(),
        ]);
    }

    public function create(): View
    {
        return $this->views->make('provider.create', [
            'categories' => $this->categories->findAll()->pluck('title', 'id'),
        ]);
    }

    public function store(ProviderRequest $request): RedirectResponse
    {
        $this->providers->create($request->validated());
        $flash = $this->generateFlash('created', 'provider');

        return $this->redirectToRouteWithFlash('providers.index', $flash);
    }

    public function edit(Provider $provider): View
    {
        return $this->views->make('provider.edit', [
            'provider' => $provider,
            'categories' => $this->categories->findAll()->pluck('title', 'id'),
        ]);
    }

    public function update(ProviderRequest $request, Provider $provider): RedirectResponse
    {
        $this->providers->update($provider, $request->validated());
        $flash = $this->generateFlash('updated', 'provider');

        return $this->redirectToRouteWithFlash('providers.index', $flash);
    }

    public function destroy(Provider $provider): RedirectResponse
    {
        $this->providers->delete($provider);
        $flash = $this->generateFlash('deleted', 'provider');

        return $this->redirectToRouteWithFlash('providers.index', $flash);
    }
}

resources/views/provider/create.blade.php
@extends('layouts.app')

@section('title', trans('sections.provider.index'))

@section('content')

  @component('forms.form', ['action' => route('providers.store')])
    @include('provider.form')

    @component('forms.submit')
      @lang('buttons.create')
    @endcomponent
  @endcomponent

@endsection

resources/views/provider/edit.blade.php
@extends('layouts.app')

@section('title', trans('sections.provider.update'))

@section('content')

  @component('forms.form', ['method' => 'PATCH', 'action' => route('providers.update', ['provider' => $provider->id])])
    @include('provider.form')

    @component('forms.submit')
      @lang('buttons.update')
    @endcomponent
  @endcomponent

@endsection

resources/views/provider/form.blade.php
@include('forms.group', [
  'name' => 'title',
  'label' => trans('labels.title'),
  'value' => $provider->title ?? null
])
@include('forms.group', [
  'type' => 'url',
  'name' => 'url',
  'label' => trans('labels.url'),
  'value' => $provider->url ?? null
])
@include('forms.group', [
  'type' => 'select',
  'name' => 'category_id',
  'label' => trans('labels.category'),
  'options' => $categories,
  'placeholder' => trans('placeholders.select.category'),
  'value' => $provider->category->id ?? null,
])

resources/views/provider/index.blade.php
@extends('layouts.app')

@section('title', trans('sections.provider.index'))

@section('actions')
  <a href="{{ route('providers.create') }}"
     class="btn btn-xs btn-success pull-right">@lang('buttons.create')</a>
@endsection

@section('content-class', 'table-responsive')

@section('content')
  <table class="table table-bordered">
    <tr>
      <th>#</th>
      <th>@lang('labels.title')</th>
      <th>@lang('labels.url')</th>
      <th></th>
    </tr>
    @forelse ($groupedProviders as $group => $providers)
      <tr class="warning">
        <td colspan="4">
          <strong>{{ $group ?: trans('labels.uncategorized') }}</strong>
        </td>
      </tr>
      @each('provider.row', $providers, 'provider')
    @empty
      @include('layouts.empty', ['cols' => 4])
    @endforelse
  </table>
@endsection

@push('scripts')
  @include('modals.delete')
  <script src="{{ asset('js/delete.js') }}"></script>
@endpush

resources/views/provider/row.blade.php
<tr>
  <td>{{ $provider->id }}</td>
  <td>{{ $provider->title }}</td>
  <td>
    <a href="{{ $provider->url }}" target="_blank">
      {{ $provider->url }}
    </a>
  </td>
  <td nowrap>
    @php($feedCount = $provider->feeds->count())
    @include('layouts.controls', [
      'edit' => route('providers.edit', ['provider' => $provider->id]),
      'delete' => route('providers.destroy', ['provider' => $provider->id]),
      'message' => $feedCount > 0 ? trans_choice('messages.feed_delete', $feedCount, ['count' => $feedCount]) : null,
    ])
  </td>
</tr>