routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'change-password'], function () {
        Route::get('', 'Auth\ChangePasswordController@showChangePasswordForm')->name('password.change');
        Route::post('', 'Auth\ChangePasswordController@changePassword');
    });

    Route::group(['middleware' => 'admin'], function () {
        Route::resource('providers', 'ProviderController', ['except' => 'show']);
        Route::resource('categories', 'CategoryController', ['except' => 'show']);
    });
});

Route::get('/', 'FeedController@index')->name('feeds.index');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property int $id
 * @property string $title
 *
 * @property Provider[]|\Illuminate\Support\Collection $providers
 */
class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
    ];

    public function providers(): HasMany
    {
        return $this->hasMany(Provider::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Repositories\Contracts\CategoryRepository;
use Illuminate\Contracts\Translation\Translator;
use Illuminate\Contracts\View\Factory as ViewFactory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\Session\Store;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * @var CategoryRepository
     */
    private $categories;

    public function __construct(
        ViewFactory $views,
        Store $session,
        Redirector $redirector,
        Translator $translator,
        CategoryRepository $categories
    ) {
        parent::__construct($views, $session, $redirector, $translator);
        $this->categories = $categories;
    }

    public function index(): View
    {
        return $this->views->make('category.index', [
            'categories' => $this->categories->findAll(),
        ]);
    }

    public function create(): View
    {
        return $this->views->make('category.create');
    }

    public function store(CategoryRequest $request): RedirectResponse
    {
        $this->categories->create($request->validated());
        $flash = $this->generateFlash('created', 'category');

        return $this->redirectToRouteWithFlash('categories.index', $flash);
    }

    public function edit(Category $category): View
    {
        return $this->views->make('category.edit', [
            'category' => $category,
        ]);
    }

    public function update(CategoryRequest $request, Category $category): RedirectResponse
    {
        $this->categories->update($category, $request->validated());
        $flash = $this->generateFlash('updated', 'category');

        return $this->redirectToRouteWithFlash('categories.index', $flash);
    }

    public function destroy(Category $category): RedirectResponse
    {
        $this->categories->delete($category);
        $flash = $this->generateFlash('deleted', 'category');

        return $this->redirectToRouteWithFlash('categories.index', $flash);
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('title', trans('sections.category.index'))

@section('content')

  @component('forms.form', ['action' => route('categories.store')])
    @include('forms.group', ['name' => 'title', 'label' => trans('labels.title')])

    @component('forms.submit')
      @lang('buttons.create')
    @endcomponent
  @endcomponent

@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('title', trans('sections.category.update'))

@section('content')

  @component('forms.form', ['method' => 'PATCH', 'action' => route('categories.update', ['category' => $category->id])])
    @include('forms.group', ['name' => 'title', 'label' => trans('labels.title'), 'value' => $category->title])

    @component('forms.submit')
      @lang('buttons.update')
    @endcomponent
  @endcomponent

@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('title', trans('sections.category.index'))

@section('actions')
  <a href="{{ route('categories.create') }}"
     class="btn btn-xs btn-success pull-right">@lang('buttons.create')</a>
@endsection

@section('content-class', 'table-responsive')

@section('content')
  <table class="table table-bordered">
    <tr>
      <th>#</th>
      <th>@lang('labels.title')</th>
      <th></th>
    </tr>
    @each('category.row', $categories, 'category', 'layouts.empty')
  </table>
@endsection

@push('scripts')
  @include('modals.delete')
  <script src="{{ asset('js/delete.js') }}"></script>
@endpush

resources/views/category/row.blade.php
<tr>
  <td>{{ $category->id }}</td>
  <td>{{ $category->title }}</td>
  <td nowrap>
    @include('layouts.controls', [
      'edit' => route('categories.edit', ['category' => $category->id]),
      'delete' => route('categories.destroy', ['category' => $category->id]),
    ])
  </td>
</tr>